# Generated by Django 4.2.11 on 2024-04-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="new",
            field=models.BooleanField(default=False),
        ),
    ]
