# Generated by Django 4.2.11 on 2024-04-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_product_old_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="2.99", max_digits=5, null=True
            ),
        ),
    ]
