# Generated by Django 4.2.11 on 2024-05-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_product_old_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/")),
                ("title", models.CharField(max_length=50)),
                ("minidesc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
