# Generated by Django 4.2.11 on 2024-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="date",
            field=models.CharField(max_length=5),
        ),
    ]
