# Generated by Django 4.2.11 on 2024-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_coupons"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="freight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default="2.99", max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default="1.99", max_digits=10),
        ),
    ]
